name: canteen_food_ordering_and_queue_management_system
description: Canteen mobile app with Firebase auth
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  http: 
  firebase_core: ^4.10.0
  firebase_auth: ^6.5.2
  shared_preferences: ^2.2.2

flutter:
  uses-material-design: true